### ISSUE TITLE
DB migrate issue

### ISSUE THREAD

**Issue by ramangreat** [cbmono/beuth-hapi-restful-api#1]
Hi There,

I am getting an issue while migrating the database. I am using mysql. The error is 

Using gulpfile ~/Documents/rest/beuth-hapi-restful-api-master/gulpfile.js
[16:22:56] Starting 'db:migrate'...
[16:22:56] 'db:migrate' errored after 301 μs
[16:22:56] Error: knex: Required configuration option 'client' is missing.
    at new Client (/Users/ATAdmin/Documents/rest/beuth-hapi-restful-api-master/node_modules/knex/lib/client.js:108:11)
    at Knex (/Users/ATAdmin/Documents/rest/beuth-hapi-restful-api-master/node_modules/knex/lib/index.js:60:34)
    at Gulp.<anonymous> (/Users/ATAdmin/Documents/rest/beuth-hapi-restful-api-master/tasks/gulp.database.js:24:14)
    at module.exports (/Users/ATAdmin/Documents/rest/beuth-hapi-restful-api-master/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/ATAdmin/Documents/rest/beuth-hapi-restful-api-master/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/ATAdmin/Documents/rest/beuth-hapi-restful-api-master/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/ATAdmin/Documents/rest/beuth-hapi-restful-api-master/node_modules/orchestrator/index.js:134:8)
    at /Users/ATAdmin/Documents/rest/beuth-hapi-restful-api-master/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "db:migrate"
npm ERR! node v6.10.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hapijs-seed-mvc@2.0.0 db:migrate: `gulp db:migrate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hapijs-seed-mvc@2.0.0 db:migrate script 'gulp db:migrate'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hapijs-seed-mvc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp db:migrate
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hapijs-seed-mvc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hapijs-seed-mvc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

Do you have an idea, what it could be?
Thanks very much.

Raman

**Comment by cbmono** [comment]
`Error: knex: Required configuration option 'client' is missing.`

You are missing your config for the DB connection. 

1. Duplicate [this file](https://github.com/cbmono/beuth-hapi-restful-api/blob/master/config/dev.js.default) and name it `dev.js`
2. Uncomment [following lines](https://github.com/cbmono/beuth-hapi-restful-api/blob/master/config/dev.js.default#L32-L38) and add your local DB connection details
3. Add your DB name [here](https://github.com/cbmono/beuth-hapi-restful-api/blob/master/config/default.js#L52)
4. Then run `export NODE_ENV=dev && npm run db:migrate`

Best,
Claudio.

**Comment by ramangreat** [comment]
HI Claudio,

Thanks very much it worked, I was missing the step - export NODE_ENV=dev.

Thanks
Raman
